// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_dummy_achievement = "CgkIypzD96oDEAIQAQ"; // <GPGSID>
        public const string achievement_bubble_blower = "CgkIypzD96oDEAIQCw"; // <GPGSID>
        public const string leaderboard_pengi_master = "CgkIypzD96oDEAIQDw"; // <GPGSID>
        public const string achievement_shopaholic = "CgkIypzD96oDEAIQCA"; // <GPGSID>
        public const string achievement_pengi_catcher = "CgkIypzD96oDEAIQBg"; // <GPGSID>
        public const string leaderboard_chicky_master = "CgkIypzD96oDEAIQDg"; // <GPGSID>
        public const string achievement_too_rich = "CgkIypzD96oDEAIQCg"; // <GPGSID>
        public const string achievement_chicky_catcher = "CgkIypzD96oDEAIQAw"; // <GPGSID>
        public const string achievement_bubble_lover = "CgkIypzD96oDEAIQDA"; // <GPGSID>
        public const string achievement_pengi_trapper = "CgkIypzD96oDEAIQBQ"; // <GPGSID>
        public const string achievement_chicky_trapper = "CgkIypzD96oDEAIQAg"; // <GPGSID>
        public const string achievement_pengi_hunter = "CgkIypzD96oDEAIQBw"; // <GPGSID>
        public const string achievement_chicky_hunter = "CgkIypzD96oDEAIQBA"; // <GPGSID>
        public const string achievement_bubble_master = "CgkIypzD96oDEAIQDQ"; // <GPGSID>
        public const string achievement_big_spender = "CgkIypzD96oDEAIQCQ"; // <GPGSID>

}

